version: 2
updates:
  # Check for updates to GitHub Actions every week
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
  # Check for updates to NuGet packages every week
  - package-ecosystem: "nuget"
    directory: "/test/Blazor.BrowserExtension.IntegrationTest/"
    allow:
    - dependency-type: "direct"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    groups:
      aspnetcore:
        patterns: [ Microsoft.AspNetCore.* ]
  - package-ecosystem: "nuget"
    directory: "/test/Blazor.BrowserExtension.IntegrationTestRunner/"
    allow:
    - dependency-type: "direct"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    groups:
      mstest:
        patterns: [ MSTest.* ]
      xunit:
        patterns: [ xunit, xunit.* ]
  - package-ecosystem: "nuget"
    directory: "/test/Blazor.BrowserExtension.Build.Test/"
    allow:
    - dependency-type: "direct"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    groups:
      xunit:
        patterns: [ xunit, xunit.* ]
